package com.nbg.android.terminal

data class UbuntuBootstrapScript(
  val filesDir: String,
  val nativeLibraryDir: String,
  val packageName: String,
) {
  companion object {
    const val UBUNTU_ARCHIVE = "ubuntu-noble-aarch64-pd-v4.18.0.tar.xz"
    const val UBUNTU_ARCHIVE_SHA256 = "91acaa786b8e2fbba56a9fd0f8a1188cee482b5c7baeed707b29ddaa9a294daa"
    const val UBUNTU_ARCHIVE_VERSION = UBUNTU_ARCHIVE + "-" + UBUNTU_ARCHIVE_SHA256
    private const val UBUNTU_VERSION = "24.04-noble-aarch64-pd-v4.18.0"
  }

  fun render(): String {
    val ubuntuRoot = "$filesDir/usr/var/lib/proot-distro/installed-rootfs/ubuntu"
    return """
      export HOME="$filesDir"
      export PREFIX="$filesDir/usr"
      export BIN="${'$'}PREFIX/bin"
      export TMPDIR="$filesDir/tmp"
      export PROOT_TMP_DIR="${'$'}TMPDIR"
      export LD_LIBRARY_PATH="$nativeLibraryDir:${'$'}PREFIX/lib:${'$'}BIN"
      export PROOT_LOADER="${'$'}BIN/loader"
      export UBUNTU_ARCHIVE="$UBUNTU_ARCHIVE"
      export UBUNTU_ARCHIVE_SHA256="$UBUNTU_ARCHIVE_SHA256"
      export NBG_NODE_ARCHIVE="${NbgCodeRuntime.nodeArchiveAssetName}"
      export UBUNTU_VERSION="$UBUNTU_VERSION"
      export UBUNTU_ROOT="$ubuntuRoot"
      export APP_PACKAGE="$packageName"
      export NBG_NATIVE_LIB_DIR="$nativeLibraryDir"
      export NBG_RG_HOST_BIN="${'$'}NBG_NATIVE_LIB_DIR/${NbgCodeRuntime.ripgrepLibraryName}"
      export NBG_UPLOADS_HOST_DIR="$filesDir/nbg-uploads"
      export NBG_ANDROID_PUBLIC_ROOT="${NBG_ANDROID_PUBLIC_ROOT}"
      export NBG_UBUNTU_ROOT_HOME="${NBG_UBUNTU_ROOT_HOME}"
      export NBG_UBUNTU_OUTPUTS_DIR="${NBG_UBUNTU_OUTPUTS_DIR}"
      export NBG_UBUNTU_BACKUPS_DIR="${NBG_UBUNTU_BACKUPS_DIR}"
      export NBG_UBUNTU_TMP_DIR="${NBG_UBUNTU_TMP_DIR}"
      export NBG_UBUNTU_BUILD_WORKSPACES_DIR="${NBG_UBUNTU_BUILD_WORKSPACES_DIR}"
      export NBG_SHARED_STORAGE_DIR="/storage/emulated/0"
      export DEFAULT_TOOLS_VERSION="node24-npm-builtin-rg15.1.0-v1"
      export DEFAULT_NODE_DIST_URL="https://nodejs.org/dist/v24.15.0"
      export DEFAULT_NODE_ARCHIVE="node-v24.15.0-linux-arm64.tar.xz"
      export DEFAULT_NODE_ARCHIVE_SHA256="${NbgCodeRuntime.nodeArchiveSha256}"

      shell_single_quote() {
        printf "%s" "${'$'}1" | "${'$'}BIN/busybox" sed "s/'/'\\\\''/g"
      }

      terminal_phase() {
        echo "NBG_TERMINAL_PHASE ${'$'}1"
      }

      write_android_proxy_profile() {
        mkdir -p "${'$'}UBUNTU_ROOT/etc/profile.d" 2>/dev/null || return 1
        proxy_profile="${'$'}UBUNTU_ROOT/etc/profile.d/01-nbg-android-proxy.sh"
        proxy_profile_tmp="${'$'}proxy_profile.tmp"
        {
          echo "# Generated by NBG Android."
          proxy_found=0
          for proxy_name in HTTP_PROXY HTTPS_PROXY ALL_PROXY NO_PROXY http_proxy https_proxy all_proxy no_proxy NPM_CONFIG_PROXY NPM_CONFIG_HTTPS_PROXY npm_config_proxy npm_config_https_proxy; do
            proxy_value="${'$'}{!proxy_name:-}"
            if [ -n "${'$'}proxy_value" ]; then
              proxy_found=1
              printf "export %s='%s'\n" "${'$'}proxy_name" "${'$'}(shell_single_quote "${'$'}proxy_value")"
            fi
          done
          if [ "${'$'}proxy_found" -eq 0 ]; then
            echo "unset HTTP_PROXY HTTPS_PROXY ALL_PROXY NO_PROXY http_proxy https_proxy all_proxy no_proxy NPM_CONFIG_PROXY NPM_CONFIG_HTTPS_PROXY npm_config_proxy npm_config_https_proxy"
          fi
        } > "${'$'}proxy_profile_tmp" || return 1
        mv "${'$'}proxy_profile_tmp" "${'$'}proxy_profile" || return 1
      }

      write_android_runtime_profile() {
        mkdir -p "${'$'}UBUNTU_ROOT/etc/profile.d" 2>/dev/null || return 1
        runtime_profile="${'$'}UBUNTU_ROOT/etc/profile.d/02-nbg-android-runtime.sh"
        runtime_profile_tmp="${'$'}runtime_profile.tmp"
        cat > "${'$'}runtime_profile_tmp" <<'EOF'
# Generated by NBG Android.
nbg_android_prepend_path() {
  case ":${'$'}PATH:" in
    *:"${'$'}1":*) ;;
    *) [ -d "${'$'}1" ] && PATH="${'$'}1:${'$'}PATH" ;;
  esac
}

nbg_android_export_proxy_aliases() {
  if [ -n "${'$'}{HTTP_PROXY:-}" ] && [ -z "${'$'}{http_proxy:-}" ]; then export http_proxy="${'$'}HTTP_PROXY"; fi
  if [ -n "${'$'}{http_proxy:-}" ] && [ -z "${'$'}{HTTP_PROXY:-}" ]; then export HTTP_PROXY="${'$'}http_proxy"; fi
  if [ -n "${'$'}{HTTPS_PROXY:-}" ] && [ -z "${'$'}{https_proxy:-}" ]; then export https_proxy="${'$'}HTTPS_PROXY"; fi
  if [ -n "${'$'}{https_proxy:-}" ] && [ -z "${'$'}{HTTPS_PROXY:-}" ]; then export HTTPS_PROXY="${'$'}https_proxy"; fi
  if [ -n "${'$'}{ALL_PROXY:-}" ] && [ -z "${'$'}{all_proxy:-}" ]; then export all_proxy="${'$'}ALL_PROXY"; fi
  if [ -n "${'$'}{all_proxy:-}" ] && [ -z "${'$'}{ALL_PROXY:-}" ]; then export ALL_PROXY="${'$'}all_proxy"; fi
  if [ -n "${'$'}{NO_PROXY:-}" ] && [ -z "${'$'}{no_proxy:-}" ]; then export no_proxy="${'$'}NO_PROXY"; fi
  if [ -n "${'$'}{no_proxy:-}" ] && [ -z "${'$'}{NO_PROXY:-}" ]; then export NO_PROXY="${'$'}no_proxy"; fi
  if [ -n "${'$'}{http_proxy:-}" ]; then
    export npm_config_proxy="${'$'}{npm_config_proxy:-${'$'}http_proxy}"
    export NPM_CONFIG_PROXY="${'$'}{NPM_CONFIG_PROXY:-${'$'}http_proxy}"
  fi
  if [ -n "${'$'}{https_proxy:-}" ]; then
    export npm_config_https_proxy="${'$'}{npm_config_https_proxy:-${'$'}https_proxy}"
    export NPM_CONFIG_HTTPS_PROXY="${'$'}{NPM_CONFIG_HTTPS_PROXY:-${'$'}https_proxy}"
  fi
}

nbg_android_prepare_random_devices() {
  case " ${'$'}{JAVA_TOOL_OPTIONS:-} " in
    *" -Djava.security.egd=file:/dev/./urandom "*) ;;
    *) export JAVA_TOOL_OPTIONS="-Djava.security.egd=file:/dev/./urandom${'$'}{JAVA_TOOL_OPTIONS:+ ${'$'}JAVA_TOOL_OPTIONS}" ;;
  esac
  case " ${'$'}{GRADLE_OPTS:-} " in
    *" -Djava.security.egd=file:/dev/./urandom "*) ;;
    *) export GRADLE_OPTS="-Djava.security.egd=file:/dev/./urandom${'$'}{GRADLE_OPTS:+ ${'$'}GRADLE_OPTS}" ;;
  esac
  if [ -c /dev/urandom ] && [ -c /dev/random ]; then
    return 0
  fi
  if [ -p /dev/urandom ] || [ -L /dev/urandom ]; then
    return 0
  fi
  [ ! -c /dev/urandom ] && [ ! -p /dev/urandom ] && [ ! -L /dev/urandom ] && rm -f /dev/urandom 2>/dev/null || true
  [ ! -c /dev/random ] && [ ! -p /dev/random ] && [ ! -L /dev/random ] && rm -f /dev/random 2>/dev/null || true
  if command -v python3 >/dev/null 2>&1 && command -v mkfifo >/dev/null 2>&1; then
    if mkfifo /dev/urandom 2>/dev/null; then
      ln -sf /dev/urandom /dev/random 2>/dev/null || true
      (
        while true; do
          python3 -c 'import os,sys
while True:
    sys.stdout.buffer.write(os.urandom(4096))
    sys.stdout.buffer.flush()
' > /dev/urandom 2>/dev/null
          sleep 0.2
        done
      ) >/dev/null 2>&1 &
      return 0
    fi
  fi
  if [ -c /dev/zero ]; then
    [ ! -e /dev/urandom ] && ln -s /dev/zero /dev/urandom 2>/dev/null || true
    [ ! -e /dev/random ] && ln -s /dev/zero /dev/random 2>/dev/null || true
  fi
}

nbg_android_detect_toolchains() {
  nbg_android_prepend_path /opt/hanakopro-server
  nbg_android_prepend_path /usr/local/node-v24/bin
  nbg_android_prepend_path /root/.local/bin
  if [ -d /opt/android-sdk ]; then
    export ANDROID_HOME="${'$'}{ANDROID_HOME:-/opt/android-sdk}"
    export ANDROID_SDK_ROOT="${'$'}{ANDROID_SDK_ROOT:-/opt/android-sdk}"
    nbg_android_prepend_path /opt/android-sdk/platform-tools
    nbg_android_prepend_path /opt/android-sdk/cmdline-tools/latest/bin
    for build_tools_dir in /opt/android-sdk/build-tools/*; do
      [ -d "${'$'}build_tools_dir" ] && nbg_android_prepend_path "${'$'}build_tools_dir"
    done
  fi
  for java_home in /usr/lib/jvm/java-21-openjdk-arm64 /usr/lib/jvm/java-17-openjdk-arm64 /opt/jdk-21 /opt/jdk-17; do
    if [ -x "${'$'}java_home/bin/java" ]; then
      export JAVA_HOME="${'$'}{JAVA_HOME:-${'$'}java_home}"
      nbg_android_prepend_path "${'$'}JAVA_HOME/bin"
      break
    fi
  done
  export PATH
}

nbg_android_fix_executables() {
  for sdk_tool in \
    /opt/android-sdk/cmdline-tools/latest/bin/sdkmanager \
    /opt/android-sdk/cmdline-tools/latest/bin/avdmanager \
    /opt/android-sdk/platform-tools/adb
  do
    [ -f "${'$'}sdk_tool" ] && chmod 755 "${'$'}sdk_tool" 2>/dev/null || true
  done
  for gradlew in /root/*/gradlew /root/*/*/gradlew /storage/emulated/0/NBG/*/gradlew /storage/emulated/0/NBG/*/*/gradlew; do
    [ -f "${'$'}gradlew" ] && chmod 755 "${'$'}gradlew" 2>/dev/null || true
  done
}

nbg_android_runtime_env() {
  nbg_android_export_proxy_aliases
  nbg_android_prepare_random_devices
  nbg_android_detect_toolchains
  nbg_android_fix_executables
}

nbg_android_runtime_env
EOF
        mv "${'$'}runtime_profile_tmp" "${'$'}runtime_profile" || return 1
      }

      write_default_dns() {
        target_file="${'$'}1"
        if [ -z "${'$'}target_file" ]; then
          return 1
        fi
        mkdir -p "${'$'}{target_file%/*}" 2>/dev/null || true
        target_tmp="${'$'}target_file.tmp"
        cat > "${'$'}target_tmp" <<'EOF'
nameserver 8.8.8.8
nameserver 1.1.1.1
nameserver 223.5.5.5
nameserver 223.6.6.6
EOF
        if [ -f "${'$'}target_file" ] && "${'$'}BIN/busybox" cmp -s "${'$'}target_tmp" "${'$'}target_file"; then
          rm -f "${'$'}target_tmp" 2>/dev/null || true
        else
          mv "${'$'}target_tmp" "${'$'}target_file" || return 1
        fi
      }

      can_access_bind_source() {
        bind_source="${'$'}1"
        if [ -z "${'$'}bind_source" ]; then
          return 1
        fi
        if [ ! -e "${'$'}bind_source" ] && [ ! -L "${'$'}bind_source" ]; then
          return 1
        fi
        "${'$'}BIN/busybox" ls -Ld "${'$'}bind_source" >/dev/null 2>&1
      }

      append_proot_bind_arg() {
        bind_source="${'$'}1"
        bind_target="${'$'}2"
        if ! can_access_bind_source "${'$'}bind_source"; then
          return 0
        fi
        if [ -z "${'$'}bind_target" ] || [ "${'$'}bind_source" = "${'$'}bind_target" ]; then
          PROOT_BIND_ARGS="${'$'}PROOT_BIND_ARGS -b ${'$'}bind_source"
        else
          PROOT_BIND_ARGS="${'$'}PROOT_BIND_ARGS -b ${'$'}bind_source:${'$'}bind_target"
        fi
      }

      setup_proot_bind_args() {
        PROOT_BIND_ARGS=""
        append_proot_bind_arg /proc /proc
        append_proot_bind_arg /dev/null /dev/null
        append_proot_bind_arg /dev/zero /dev/zero
        append_proot_bind_arg /dev/random /dev/random
        append_proot_bind_arg /dev/urandom /dev/urandom
        append_proot_bind_arg /sdcard /sdcard
        append_proot_bind_arg "${'$'}NBG_SHARED_STORAGE_DIR" "${'$'}NBG_SHARED_STORAGE_DIR"
        append_proot_bind_arg "${'$'}NBG_ANDROID_PUBLIC_ROOT" "${'$'}NBG_ANDROID_PUBLIC_ROOT"
        append_proot_bind_arg "${'$'}HOME" "${'$'}HOME"
        append_proot_bind_arg "${'$'}NBG_UPLOADS_HOST_DIR" /root/nbg-uploads
      }

      prepare_ubuntu_home() {
        mkdir -p "${'$'}NBG_UPLOADS_HOST_DIR" 2>/dev/null || true
        mkdir -p \
          "${'$'}UBUNTU_ROOT${'$'}NBG_UBUNTU_ROOT_HOME" \
          "${'$'}UBUNTU_ROOT${'$'}NBG_UBUNTU_OUTPUTS_DIR" \
          "${'$'}UBUNTU_ROOT${'$'}NBG_UBUNTU_BACKUPS_DIR" \
          "${'$'}UBUNTU_ROOT${'$'}NBG_UBUNTU_TMP_DIR" \
          "${'$'}UBUNTU_ROOT${'$'}NBG_UBUNTU_BUILD_WORKSPACES_DIR" \
          2>/dev/null || true
      }

      prepare_shared_storage_links() {
        mkdir -p "${'$'}NBG_ANDROID_PUBLIC_ROOT" 2>/dev/null || true
        mkdir -p "${'$'}UBUNTU_ROOT${'$'}NBG_SHARED_STORAGE_DIR" 2>/dev/null || true
      }

      install_ubuntu() {
        OK_FILE="${'$'}UBUNTU_ROOT/.nbg_installed_ok"
        VERSION_FILE="${'$'}UBUNTU_ROOT/.nbg_ubuntu_version"
        LOCK_DIR="${'$'}UBUNTU_ROOT.install.lock"
        LOCK_PID_FILE="${'$'}LOCK_DIR/pid"
        TMP_ROOT="${'$'}UBUNTU_ROOT.install.tmp"

        mkdir -p "${'$'}PREFIX/bin" "${'$'}TMPDIR" "${'$'}{UBUNTU_ROOT%/*}" 2>/dev/null || true

        installed_version_fast=""
        if [ -f "${'$'}VERSION_FILE" ]; then
          installed_version_fast="${'$'}(cat "${'$'}VERSION_FILE" 2>/dev/null)"
        fi
        if [ -f "${'$'}OK_FILE" ] && [ "${'$'}installed_version_fast" = "${'$'}UBUNTU_VERSION" ]; then
          mkdir -p "${'$'}UBUNTU_ROOT/etc" 2>/dev/null || true
          mkdir -p "${'$'}UBUNTU_ROOT/root/nbg-uploads" "${'$'}UBUNTU_ROOT/sdcard" "${'$'}UBUNTU_ROOT/tmp" "${'$'}UBUNTU_ROOT/dev/pts" "${'$'}UBUNTU_ROOT/dev/shm" 2>/dev/null || true
          touch "${'$'}UBUNTU_ROOT/dev/null" "${'$'}UBUNTU_ROOT/dev/zero" "${'$'}UBUNTU_ROOT/dev/random" "${'$'}UBUNTU_ROOT/dev/urandom" "${'$'}UBUNTU_ROOT/dev/tty" "${'$'}UBUNTU_ROOT/dev/console" "${'$'}UBUNTU_ROOT/dev/full" "${'$'}UBUNTU_ROOT/dev/ptmx" 2>/dev/null || true
          write_default_dns "${'$'}UBUNTU_ROOT/etc/resolv.conf"
          return 0
        fi

        attempt=0
        while true; do
          if mkdir "${'$'}LOCK_DIR" 2>/dev/null; then
            echo "${'$'}${'$'}" > "${'$'}LOCK_PID_FILE" 2>/dev/null || true
            break
          fi

          if [ -f "${'$'}LOCK_PID_FILE" ]; then
            lock_pid="${'$'}(cat "${'$'}LOCK_PID_FILE" 2>/dev/null)"
            if [ -z "${'$'}lock_pid" ] || ! kill -0 "${'$'}lock_pid" 2>/dev/null; then
              rm -rf "${'$'}LOCK_DIR" 2>/dev/null || true
              continue
            fi
          elif [ "${'$'}attempt" -gt 2 ]; then
            rm -rf "${'$'}LOCK_DIR" 2>/dev/null || true
            continue
          fi

          attempt="${'$'}((attempt + 1))"
          if [ "${'$'}attempt" -gt 120 ]; then
            echo "Ubuntu install lock timeout"
            return 1
          fi
          sleep 1
        done

        cleanup_install() {
          rm -rf "${'$'}TMP_ROOT" 2>/dev/null || true
          rm -rf "${'$'}LOCK_DIR" 2>/dev/null || true
        }
        trap 'cleanup_install' EXIT INT TERM

        installed_version=""
        if [ -f "${'$'}VERSION_FILE" ]; then
          installed_version="${'$'}(cat "${'$'}VERSION_FILE" 2>/dev/null)"
        fi

        if [ ! -f "${'$'}OK_FILE" ] || [ "${'$'}installed_version" != "${'$'}UBUNTU_VERSION" ]; then
          ubuntu_archive_path="${'$'}HOME/${'$'}UBUNTU_ARCHIVE"
          if [ ! -f "${'$'}ubuntu_archive_path" ]; then
            echo "Missing Ubuntu archive: ${'$'}ubuntu_archive_path" >&2
            cleanup_install
            trap - EXIT INT TERM
            return 1
          fi
          actual_ubuntu_sha="${'$'}("${'$'}BIN/busybox" sha256sum "${'$'}ubuntu_archive_path" 2>/dev/null | "${'$'}BIN/busybox" awk '{ print ${'$'}1; exit }')"
          if [ -z "${'$'}actual_ubuntu_sha" ]; then
            echo "Unable to verify Ubuntu archive checksum: ${'$'}ubuntu_archive_path" >&2
            cleanup_install
            trap - EXIT INT TERM
            return 1
          fi
          if [ "${'$'}actual_ubuntu_sha" != "${'$'}UBUNTU_ARCHIVE_SHA256" ]; then
            echo "Ubuntu archive checksum mismatch: ${'$'}UBUNTU_ARCHIVE" >&2
            echo "expected_sha256=${'$'}UBUNTU_ARCHIVE_SHA256" >&2
            echo "actual_sha256=${'$'}actual_ubuntu_sha" >&2
            rm -f "${'$'}ubuntu_archive_path" 2>/dev/null || true
            cleanup_install
            trap - EXIT INT TERM
            return 1
          fi
          rm -rf "${'$'}TMP_ROOT" 2>/dev/null || true
          mkdir -p "${'$'}TMP_ROOT" 2>/dev/null || true
          "${'$'}BIN/busybox" tar xf "${'$'}ubuntu_archive_path" -C "${'$'}UBUNTU_ROOT.install.tmp" 2> "${'$'}TMPDIR/install_ubuntu.err"
          if [ "${'$'}?" -ne 0 ]; then
            cat "${'$'}TMPDIR/install_ubuntu.err" >&2 2>/dev/null || true
            cleanup_install
            trap - EXIT INT TERM
            return 1
          fi
          if [ -d "${'$'}TMP_ROOT/ubuntu-noble-aarch64" ]; then
            mv "${'$'}TMP_ROOT/ubuntu-noble-aarch64"/* "${'$'}TMP_ROOT"/ 2>/dev/null || true
            rm -rf "${'$'}TMP_ROOT/ubuntu-noble-aarch64" 2>/dev/null || true
          fi
          mkdir -p "${'$'}TMP_ROOT/root/nbg-uploads" "${'$'}TMP_ROOT/sdcard" "${'$'}TMP_ROOT/tmp" "${'$'}TMP_ROOT/dev/pts" "${'$'}TMP_ROOT/dev/shm" "${'$'}TMP_ROOT/etc" 2>/dev/null || true
          touch "${'$'}TMP_ROOT/dev/null" "${'$'}TMP_ROOT/dev/zero" "${'$'}TMP_ROOT/dev/random" "${'$'}TMP_ROOT/dev/urandom" "${'$'}TMP_ROOT/dev/tty" "${'$'}TMP_ROOT/dev/console" "${'$'}TMP_ROOT/dev/full" "${'$'}TMP_ROOT/dev/ptmx" 2>/dev/null || true
          write_default_dns "${'$'}TMP_ROOT/etc/resolv.conf"
          echo ok > "${'$'}TMP_ROOT/.nbg_installed_ok"
          echo "${'$'}UBUNTU_VERSION" > "${'$'}TMP_ROOT/.nbg_ubuntu_version"
          rm -rf "${'$'}UBUNTU_ROOT" 2>/dev/null || true
          mv "${'$'}TMP_ROOT" "${'$'}UBUNTU_ROOT"
          if [ "${'$'}?" -ne 0 ]; then
            cleanup_install
            trap - EXIT INT TERM
            return 1
          fi
        fi

        mkdir -p "${'$'}UBUNTU_ROOT/etc" 2>/dev/null || true
        mkdir -p "${'$'}UBUNTU_ROOT/root/nbg-uploads" "${'$'}UBUNTU_ROOT/sdcard" "${'$'}UBUNTU_ROOT/tmp" "${'$'}UBUNTU_ROOT/dev/pts" "${'$'}UBUNTU_ROOT/dev/shm" 2>/dev/null || true
        touch "${'$'}UBUNTU_ROOT/dev/null" "${'$'}UBUNTU_ROOT/dev/zero" "${'$'}UBUNTU_ROOT/dev/random" "${'$'}UBUNTU_ROOT/dev/urandom" "${'$'}UBUNTU_ROOT/dev/tty" "${'$'}UBUNTU_ROOT/dev/console" "${'$'}UBUNTU_ROOT/dev/full" "${'$'}UBUNTU_ROOT/dev/ptmx" 2>/dev/null || true
        write_default_dns "${'$'}UBUNTU_ROOT/etc/resolv.conf"
        echo "${'$'}UBUNTU_VERSION" > "${'$'}UBUNTU_ROOT/.nbg_ubuntu_version"
        rm -rf "${'$'}LOCK_DIR" 2>/dev/null || true
        trap - EXIT INT TERM
      }

      install_android_build_helper() {
        build_wrapper="${'$'}UBUNTU_ROOT/usr/local/bin/android-build"
        mkdir -p "${'$'}{build_wrapper%/*}" 2>/dev/null || true
        build_wrapper_tmp="${'$'}build_wrapper.tmp"
        cat > "${'$'}build_wrapper_tmp" <<'EOF'
#!/bin/bash
set -euo pipefail

usage() {
  echo "Usage: android-build [project-dir-under-/root-or-name] -- <build command>" >&2
}

project_arg="${'$'}{1:-}"
if [ "${'$'}project_arg" = "--" ]; then
  public_project="${'$'}PWD"
  shift 1
elif [ -n "${'$'}project_arg" ] && [ "${'$'}{2:-}" = "--" ]; then
  case "${'$'}project_arg" in
    /*) public_project="${'$'}project_arg" ;;
    *) public_project="${'$'}PWD/${'$'}project_arg" ;;
  esac
  shift 2
else
  usage
  exit 2
fi
if [ "${'$'}#" -eq 0 ]; then
  usage
  exit 2
fi

if [ ! -d "${'$'}public_project" ]; then
  echo "Project not found: ${'$'}public_project" >&2
  exit 2
fi
public_project="${'$'}(cd "${'$'}public_project" && pwd)"

case "${'$'}public_project" in
  /root|/root/*) ;;
  *) echo "Project must be under /root" >&2; exit 2 ;;
esac

project_name="${'$'}(basename "${'$'}public_project")"
build_root="/root/build-workspaces"
build_project="${'$'}build_root/${'$'}project_name"
output_dir="/root/outputs/${'$'}project_name"
mkdir -p "${'$'}build_root" "${'$'}output_dir"
rm -rf "${'$'}build_project"
mkdir -p "${'$'}build_project"

copy_project() {
  if command -v rsync >/dev/null 2>&1; then
    rsync -a --delete \
      --exclude node_modules \
      --exclude .gradle \
      --exclude .cache \
      --exclude .npm \
      --exclude .cargo \
      --exclude build \
      --exclude dist \
      --exclude target \
      --exclude outputs \
      --exclude backups \
      --exclude tmp \
      --exclude build-workspaces \
      "${'$'}public_project"/ "${'$'}build_project"/
  else
    (cd "${'$'}public_project" && tar cf - \
      --exclude='./node_modules' \
      --exclude='./.gradle' \
      --exclude='./.cache' \
      --exclude='./.npm' \
      --exclude='./.cargo' \
      --exclude='./build' \
      --exclude='./dist' \
      --exclude='./target' \
      --exclude='./outputs' \
      --exclude='./backups' \
      --exclude='./tmp' \
      --exclude='./build-workspaces' \
      .) | (cd "${'$'}build_project" && tar xf -)
  fi
}

sync_outputs() {
  mkdir -p "${'$'}output_dir"
  for path in build dist target out app/build/outputs; do
    if [ -e "${'$'}build_project/${'$'}path" ]; then
      output_parent="${'$'}output_dir/${'$'}(dirname "${'$'}path")"
      mkdir -p "${'$'}output_parent" 2>/dev/null || true
      cp -a "${'$'}build_project/${'$'}path" "${'$'}output_parent/" 2>/dev/null || true
    fi
  done
  find "${'$'}build_project" -maxdepth 3 -type f \( \
    -name '*.apk' -o -name '*.aab' -o -name '*.aar' -o -name '*.jar' -o \
    -name '*.so' -o -name '*.ko' -o -name '*.bin' -o -perm -111 \
  \) -exec cp -a {} "${'$'}output_dir"/ \; 2>/dev/null || true
}

copy_project
cd "${'$'}build_project"
export GOCACHE=/root/.cache/go-build
export GOMODCACHE=/root/.cache/go-mod
export GRADLE_USER_HOME=/root/.gradle
export NPM_CONFIG_CACHE=/root/.npm
export CARGO_HOME=/root/.cargo
export TMPDIR=/tmp

. /etc/profile.d/01-nbg-android-proxy.sh 2>/dev/null || true
. /etc/profile.d/02-nbg-android-runtime.sh 2>/dev/null || true

set +e
"${'$'}@"
status="${'$'}?"
set -e
sync_outputs
echo "Outputs: ${'$'}output_dir"
exit "${'$'}status"
EOF
        if [ -f "${'$'}build_wrapper" ] && "${'$'}BIN/busybox" cmp -s "${'$'}build_wrapper_tmp" "${'$'}build_wrapper"; then
          rm -f "${'$'}build_wrapper_tmp" 2>/dev/null || true
        else
          mv "${'$'}build_wrapper_tmp" "${'$'}build_wrapper" || return 1
          chmod 755 "${'$'}build_wrapper"
        fi
      }

      write_full_ubuntu_sources() {
        mkdir -p "${'$'}UBUNTU_ROOT/etc/apt" 2>/dev/null || true
        cat <<'EOF' > "${'$'}UBUNTU_ROOT/etc/apt/sources.list"
# From NBG Android default source profile
deb https://mirrors.tuna.tsinghua.edu.cn/ubuntu-ports/ noble main restricted universe multiverse
deb https://mirrors.tuna.tsinghua.edu.cn/ubuntu-ports/ noble-updates main restricted universe multiverse
deb https://mirrors.tuna.tsinghua.edu.cn/ubuntu-ports/ noble-backports main restricted universe multiverse
deb https://mirrors.tuna.tsinghua.edu.cn/ubuntu-ports/ noble-security main restricted universe multiverse
EOF
      }

      write_base_ubuntu_sources() {
        mkdir -p "${'$'}UBUNTU_ROOT/etc/apt" 2>/dev/null || true
        cat <<'EOF' > "${'$'}UBUNTU_ROOT/etc/apt/sources.list"
# From NBG Android base source profile used while installing default tools
deb https://mirrors.tuna.tsinghua.edu.cn/ubuntu-ports/ noble main restricted universe multiverse
EOF
      }

      configure_package_sources() {
        write_android_proxy_profile || return 1
        write_android_runtime_profile || return 1
        write_full_ubuntu_sources
        mkdir -p "${'$'}UBUNTU_ROOT/root/.config/pip" "${'$'}UBUNTU_ROOT/root/.config/uv" 2>/dev/null || true
        echo '[global]' > "${'$'}UBUNTU_ROOT/root/.config/pip/pip.conf"
        echo 'index-url = https://pypi.tuna.tsinghua.edu.cn/simple' >> "${'$'}UBUNTU_ROOT/root/.config/pip/pip.conf"
        echo 'index-url = "https://pypi.tuna.tsinghua.edu.cn/simple"' > "${'$'}UBUNTU_ROOT/root/.config/uv/uv.toml"

        configure_npm_defaults || return 1
      }

      configure_npm_defaults() {
        mkdir -p "${'$'}UBUNTU_ROOT/root" 2>/dev/null || true
        {
          echo 'prefix=/usr/local'
          echo 'registry=https://registry.npmmirror.com/'
        } > "${'$'}UBUNTU_ROOT/root/.npmrc"
      }

      fix_android_group_names() {
        mkdir -p "${'$'}UBUNTU_ROOT/etc" 2>/dev/null || true
        touch "${'$'}UBUNTU_ROOT/etc/group" 2>/dev/null || true
        current_groups="${'$'}(id -G 2>/dev/null || true)"
        for gid in ${'$'}current_groups; do
          case "${'$'}gid" in
            ''|*[!0-9]*) continue ;;
          esac
          if ! grep -q ":${'$'}gid:" "${'$'}UBUNTU_ROOT/etc/group" 2>/dev/null; then
            echo "android_group_${'$'}gid:x:${'$'}gid:" >> "${'$'}UBUNTU_ROOT/etc/group"
          fi
        done
      }

      LAST_PROOT_PROBE_STATUS=0
      LAST_PROOT_PROBE_OUTPUT=""

      run_proot_probe() {
        LAST_PROOT_PROBE_OUTPUT="${'$'}(
          "${'$'}BIN/proot" \
            -v 1 \
            -0 \
            --link2symlink \
            --kill-on-exit \
            -r "${'$'}UBUNTU_ROOT" \
            ${'$'}PROOT_BIND_ARGS \
            -w "${'$'}NBG_UBUNTU_ROOT_HOME" \
            /usr/bin/env -i \
              HOME=/root \
              PWD="${'$'}NBG_UBUNTU_ROOT_HOME" \
              TERM=xterm-256color \
              LANG=en_US.UTF-8 \
              PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin \
              /bin/bash --noprofile --norc -c 'exit 0' 2>&1
        )"
        LAST_PROOT_PROBE_STATUS="${'$'}?"
        return "${'$'}LAST_PROOT_PROBE_STATUS"
      }

      print_last_proot_probe_failure() {
        echo "PRoot startup probe failed."
        echo "exit_code=${'$'}LAST_PROOT_PROBE_STATUS"
        echo "ubuntu_root=${'$'}UBUNTU_ROOT"
        echo "proot_loader=${'$'}{PROOT_LOADER:-<unset>}"
        echo "ld_library_path=${'$'}{LD_LIBRARY_PATH:-<unset>}"
        echo "bind_args=${'$'}{PROOT_BIND_ARGS:-<none>}"
        echo "--- proot stdout/stderr begin ---"
        if [ -n "${'$'}LAST_PROOT_PROBE_OUTPUT" ]; then
          printf '%s\n' "${'$'}LAST_PROOT_PROBE_OUTPUT"
        else
          echo "<empty>"
        fi
        echo "--- proot stdout/stderr end ---"
      }

      run_in_ubuntu() {
        command_to_exec="${'$'}1"
        prepare_ubuntu_home
        prepare_shared_storage_links
        setup_proot_bind_args
        write_android_proxy_profile || return 1
        write_android_runtime_profile || return 1
        if ! run_proot_probe; then
          print_last_proot_probe_failure
          return 1
        fi
        "${'$'}BIN/proot" \
          -0 \
          --link2symlink \
          -r "${'$'}UBUNTU_ROOT" \
          ${'$'}PROOT_BIND_ARGS \
          -w "${'$'}NBG_UBUNTU_ROOT_HOME" \
          /usr/bin/env -i \
            DEBIAN_FRONTEND=noninteractive \
            HOME=/root \
            PWD="${'$'}NBG_UBUNTU_ROOT_HOME" \
            GOCACHE=/root/.cache/go-build \
            GOMODCACHE=/root/.cache/go-mod \
            GRADLE_USER_HOME=/root/.gradle \
            NPM_CONFIG_CACHE=/root/.npm \
            CARGO_HOME=/root/.cargo \
            TMPDIR=/tmp \
            TERM=xterm-256color \
            LANG=en_US.UTF-8 \
            PATH=/usr/local/node-v24/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/root/.local/bin \
            COMMAND_TO_EXEC="${'$'}command_to_exec" \
            /bin/bash -lc '. /etc/profile.d/01-nbg-android-proxy.sh 2>/dev/null || true; . /etc/profile.d/02-nbg-android-runtime.sh 2>/dev/null || true; eval "${'$'}COMMAND_TO_EXEC"'
      }

      configure_node_runtime_environment() {
        mkdir -p "${'$'}UBUNTU_ROOT/etc/profile.d" 2>/dev/null || return 1
        cat > "${'$'}UBUNTU_ROOT/etc/profile.d/00-nbg-node-path.sh" <<'EOF'
case ":${'$'}PATH:" in
  *:/usr/local/node-v24/bin:*) ;;
  *) PATH="/usr/local/node-v24/bin:${'$'}PATH" ;;
esac
export PATH
EOF
      }

      node_runtime_ready() {
        configure_node_runtime_environment || return 1
        configure_npm_defaults || return 1
        if [ ! -x "${'$'}UBUNTU_ROOT/usr/local/node-v24/bin/node" ]; then
          rm -f "${'$'}UBUNTU_ROOT/.nbg_default_tools_version" 2>/dev/null || true
          return 1
        fi
        run_in_ubuntu 'test -x /usr/local/node-v24/bin/node && test -x /usr/local/node-v24/bin/npm && node --version >/dev/null 2>&1 && npm --version >/dev/null 2>&1'
      }

      ripgrep_runtime_ready() {
        run_in_ubuntu 'command -v rg >/dev/null 2>&1 && rg --version 2>/dev/null | grep -q "ripgrep 15[.]1[.]0"'
      }

      acquire_default_tools_lock() {
        tools_lock_dir="${'$'}UBUNTU_ROOT/.nbg_default_tools.lock"
        tools_lock_pid_file="${'$'}tools_lock_dir/pid"
        tools_lock_attempt=0
        while true; do
          if mkdir "${'$'}tools_lock_dir" 2>/dev/null; then
            echo "${'$'}${'$'}" > "${'$'}tools_lock_pid_file" 2>/dev/null || true
            return 0
          fi

          if [ -f "${'$'}tools_lock_pid_file" ]; then
            tools_lock_pid="${'$'}(cat "${'$'}tools_lock_pid_file" 2>/dev/null)"
            if [ -z "${'$'}tools_lock_pid" ] || ! kill -0 "${'$'}tools_lock_pid" 2>/dev/null; then
              rm -rf "${'$'}tools_lock_dir" 2>/dev/null || true
              continue
            fi
          elif [ "${'$'}tools_lock_attempt" -gt 2 ]; then
            rm -rf "${'$'}tools_lock_dir" 2>/dev/null || true
            continue
          fi

          tools_lock_attempt="${'$'}((tools_lock_attempt + 1))"
          if [ "${'$'}tools_lock_attempt" -gt 180 ]; then
            echo "Default development tool install lock timeout" >&2
            return 1
          fi
          sleep 1
        done
      }

      release_default_tools_lock() {
        rm -rf "${'$'}UBUNTU_ROOT/.nbg_default_tools.lock" 2>/dev/null || true
      }

      install_node_from_official_tarball() {
        node_work_dir="${'$'}TMPDIR/default-node-${'$'}${'$'}"
        node_archive_name="${'$'}DEFAULT_NODE_ARCHIVE"
        node_archive="${'$'}node_work_dir/${'$'}node_archive_name"
        node_root="${'$'}UBUNTU_ROOT/usr/local/node-v24"
        node_tmp_root="${'$'}UBUNTU_ROOT/usr/local/node-v24.tmp"
        node_backup_root="${'$'}UBUNTU_ROOT/usr/local/node-v24.backup"
        node_tar_err="${'$'}node_work_dir/tar.err"

        rm -f "${'$'}UBUNTU_ROOT/.nbg_default_tools_version" 2>/dev/null || true
        rm -rf "${'$'}TMPDIR/default-node" "${'$'}TMPDIR"/default-node-* "${'$'}node_tmp_root" 2>/dev/null || true
        mkdir -p "${'$'}node_work_dir" "${'$'}UBUNTU_ROOT/usr/local/bin" 2>/dev/null || return 1

        terminal_phase node_runtime
        if [ -f "${'$'}HOME/${'$'}NBG_NODE_ARCHIVE" ]; then
          echo "Installing built-in Node.js runtime..."
          cp "${'$'}HOME/${'$'}NBG_NODE_ARCHIVE" "${'$'}node_archive" || return 1
        else
          echo "Built-in Node.js archive missing; downloading ${'$'}node_archive_name from ${'$'}DEFAULT_NODE_DIST_URL"
          if ! "${'$'}BIN/busybox" wget --no-check-certificate -O "${'$'}node_archive" "${'$'}DEFAULT_NODE_DIST_URL/${'$'}node_archive_name"; then
            echo "Failed to download Node.js tarball ${'$'}node_archive_name" >&2
            return 1
          fi
        fi

        actual_sha="${'$'}("${'$'}BIN/busybox" sha256sum "${'$'}node_archive" 2>/dev/null | "${'$'}BIN/busybox" awk '{ print ${'$'}1; exit }')"
        if [ -z "${'$'}actual_sha" ]; then
          echo "Unable to calculate Node.js tarball checksum" >&2
          return 1
        fi
        if [ "${'$'}actual_sha" != "${'$'}DEFAULT_NODE_ARCHIVE_SHA256" ]; then
          echo "Node.js tarball checksum mismatch for ${'$'}node_archive_name" >&2
          return 1
        fi

        node_tar_status=0
        if ! "${'$'}BIN/busybox" tar xf "${'$'}node_archive" -C "${'$'}node_work_dir" 2> "${'$'}node_tar_err"; then
          node_tar_status=1
          echo "Node.js tarball extraction reported errors for ${'$'}node_archive_name" >&2
          cat "${'$'}node_tar_err" >&2 2>/dev/null || true
        fi
        extracted_node_dir="${'$'}node_work_dir/${'$'}{node_archive_name%.tar.xz}"
        if [ ! -d "${'$'}extracted_node_dir" ]; then
          echo "Node.js tarball did not contain ${'$'}{node_archive_name%.tar.xz}" >&2
          return 1
        fi
        if [ "${'$'}node_tar_status" -ne 0 ] && [ ! -f "${'$'}extracted_node_dir/bin/node" ]; then
          echo "Failed to extract Node.js tarball ${'$'}node_archive_name" >&2
          return 1
        fi
        rm -f \
          "${'$'}extracted_node_dir/bin/npm" \
          "${'$'}extracted_node_dir/bin/npx" \
          "${'$'}extracted_node_dir/bin/corepack" \
          2>/dev/null || true
        ln -sf "../lib/node_modules/npm/bin/npm-cli.js" "${'$'}extracted_node_dir/bin/npm"
        ln -sf "../lib/node_modules/npm/bin/npx-cli.js" "${'$'}extracted_node_dir/bin/npx"
        ln -sf "../lib/node_modules/corepack/dist/corepack.js" "${'$'}extracted_node_dir/bin/corepack"
        if [ ! -f "${'$'}extracted_node_dir/bin/node" ]; then
          echo "Node.js tarball extraction did not create bin/node" >&2
          ls -la "${'$'}extracted_node_dir/bin" >&2 2>/dev/null || true
          return 1
        fi
        chmod 755 "${'$'}extracted_node_dir/bin/node" 2>/dev/null || true

        rm -rf "${'$'}node_tmp_root" "${'$'}node_backup_root" 2>/dev/null || true
        mv "${'$'}extracted_node_dir" "${'$'}node_tmp_root" || return 1
        if [ -d "${'$'}node_root" ]; then
          mv "${'$'}node_root" "${'$'}node_backup_root" || return 1
        fi
        if ! mv "${'$'}node_tmp_root" "${'$'}node_root"; then
          echo "Failed to install Node.js into ${'$'}node_root" >&2
          if [ -d "${'$'}node_backup_root" ] && [ ! -d "${'$'}node_root" ]; then
            mv "${'$'}node_backup_root" "${'$'}node_root" 2>/dev/null || true
          fi
          return 1
        fi

        ln -sf "../node-v24/bin/node" "${'$'}UBUNTU_ROOT/usr/local/bin/node"
        ln -sf "../node-v24/bin/npm" "${'$'}UBUNTU_ROOT/usr/local/bin/npm"
        if [ -e "${'$'}node_root/bin/npx" ]; then
          ln -sf "../node-v24/bin/npx" "${'$'}UBUNTU_ROOT/usr/local/bin/npx"
        fi
        if [ -e "${'$'}node_root/bin/corepack" ]; then
          ln -sf "../node-v24/bin/corepack" "${'$'}UBUNTU_ROOT/usr/local/bin/corepack"
        fi

        if ! configure_node_runtime_environment; then
          echo "Failed to configure Node.js PATH profile" >&2
          rm -rf "${'$'}node_root" 2>/dev/null || true
          if [ -d "${'$'}node_backup_root" ]; then
            mv "${'$'}node_backup_root" "${'$'}node_root" 2>/dev/null || true
          fi
          return 1
        fi
        if ! configure_npm_defaults; then
          echo "Failed to configure npm defaults" >&2
          rm -rf "${'$'}node_root" 2>/dev/null || true
          if [ -d "${'$'}node_backup_root" ]; then
            mv "${'$'}node_backup_root" "${'$'}node_root" 2>/dev/null || true
          fi
          return 1
        fi
        if ! node_runtime_ready; then
          echo "Node.js installation did not pass runtime verification" >&2
          rm -rf "${'$'}node_root" 2>/dev/null || true
          if [ -d "${'$'}node_backup_root" ]; then
            mv "${'$'}node_backup_root" "${'$'}node_root" 2>/dev/null || true
          fi
          return 1
        fi
        rm -rf "${'$'}node_backup_root" 2>/dev/null || true
        rm -rf "${'$'}node_work_dir" 2>/dev/null || true
      }

      install_builtin_ripgrep() {
        if ripgrep_runtime_ready; then
          return 0
        fi
        if [ ! -f "${'$'}NBG_RG_HOST_BIN" ]; then
          echo "Missing built-in ripgrep binary: ${'$'}NBG_RG_HOST_BIN" >&2
          return 1
        fi

        target="${'$'}UBUNTU_ROOT/usr/local/bin/rg"
        mkdir -p "${'$'}{target%/*}" 2>/dev/null || return 1
        cp "${'$'}NBG_RG_HOST_BIN" "${'$'}target" || return 1
        chmod 755 "${'$'}target" || return 1
        ripgrep_runtime_ready
      }

      default_development_tools_ready() {
        marker="${'$'}UBUNTU_ROOT/.nbg_default_tools_version"
        if [ ! -f "${'$'}marker" ] || [ "${'$'}(cat "${'$'}marker" 2>/dev/null)" != "${'$'}DEFAULT_TOOLS_VERSION" ]; then
          return 1
        fi
        node_runtime_ready
      }

      ensure_default_development_tools() {
        if default_development_tools_ready; then
          install_builtin_ripgrep || return 1
          return 0
        fi

        if ! acquire_default_tools_lock; then
          return 1
        fi
        if default_development_tools_ready; then
          release_default_tools_lock
          install_builtin_ripgrep || return 1
          return 0
        fi

        echo "Preparing built-in development tools..."
        if ! node_runtime_ready; then
          install_node_from_official_tarball
          status="${'$'}?"
          if [ "${'$'}status" -ne 0 ]; then
            rm -f "${'$'}UBUNTU_ROOT/.nbg_default_tools_version" 2>/dev/null || true
            echo "Default development tool installation failed" >&2
            release_default_tools_lock
            return "${'$'}status"
          fi
        fi
        if ! install_builtin_ripgrep; then
          rm -f "${'$'}UBUNTU_ROOT/.nbg_default_tools_version" 2>/dev/null || true
          release_default_tools_lock
          return 1
        fi
        echo "${'$'}DEFAULT_TOOLS_VERSION" > "${'$'}UBUNTU_ROOT/.nbg_default_tools_version"
        release_default_tools_lock
      }

      login_ubuntu() {
        command_to_exec="${'$'}1"
        if [ -z "${'$'}command_to_exec" ]; then
          command_to_exec="/bin/bash -il"
        fi
        if [ -f "${'$'}HOME/setup_fake_sysdata.sh" ]; then
          export INSTALLED_ROOTFS_DIR="${'$'}{UBUNTU_ROOT%/*}"
          export distro_name="${'$'}{UBUNTU_ROOT##*/}"
          . "${'$'}HOME/setup_fake_sysdata.sh"
          setup_fake_sysdata
        fi
        prepare_ubuntu_home
        prepare_shared_storage_links
        setup_proot_bind_args
        write_android_proxy_profile || return 1
        write_android_runtime_profile || return 1
        if ! run_proot_probe; then
          print_last_proot_probe_failure
          return 1
        fi
        exec "${'$'}BIN/proot" \
          -0 \
          --link2symlink \
          --kill-on-exit \
          -r "${'$'}UBUNTU_ROOT" \
          ${'$'}PROOT_BIND_ARGS \
          -w "${'$'}NBG_UBUNTU_ROOT_HOME" \
          /usr/bin/env -i \
            HOME=/root \
            PWD="${'$'}NBG_UBUNTU_ROOT_HOME" \
            GOCACHE=/root/.cache/go-build \
            GOMODCACHE=/root/.cache/go-mod \
            GRADLE_USER_HOME=/root/.gradle \
            NPM_CONFIG_CACHE=/root/.npm \
            CARGO_HOME=/root/.cargo \
            TMPDIR=/tmp \
            TERM=xterm-256color \
            LANG=en_US.UTF-8 \
            PATH=/usr/local/node-v24/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/root/.local/bin \
            /bin/bash -lc ". /etc/profile.d/01-nbg-android-proxy.sh 2>/dev/null || true; . /etc/profile.d/02-nbg-android-runtime.sh 2>/dev/null || true; echo NBG_TERMINAL_READY; exec ${'$'}command_to_exec"
      }

      start_shell() {
        terminal_phase ubuntu_install
        install_ubuntu || exit 1
        install_android_build_helper || exit 1
        configure_package_sources || exit 1
        fix_android_group_names || exit 1
        terminal_phase development_tools
        ensure_default_development_tools || exit 1
        terminal_phase proot_probe
        login_ubuntu
      }
    """.trimIndent()
  }
}
