package com.nbg.android

import android.content.Context
import java.io.File

internal interface NbgLearnedSkillDraftStorage {
  fun read(): String?
  fun write(raw: String)
}

internal class NbgSharedPreferencesLearnedSkillDraftStorage(context: Context) : NbgLearnedSkillDraftStorage {
  private val prefs = context.applicationContext.getSharedPreferences(PREFS, Context.MODE_PRIVATE)

  override fun read(): String? =
    prefs.getString(KEY_QUEUE, null)

  override fun write(raw: String) {
    prefs.edit().putString(KEY_QUEUE, raw).apply()
  }

  private companion object {
    const val PREFS = "nbg_learned_skill_drafts"
    const val KEY_QUEUE = "queue"
  }
}

internal class NbgLearnedSkillDraftStore(
  private val storage: NbgLearnedSkillDraftStorage,
  private val artifactRoot: File? = null,
) {
  constructor(context: Context) : this(
    storage = NbgSharedPreferencesLearnedSkillDraftStorage(context),
    artifactRoot = File(context.applicationContext.filesDir, "learned-skills"),
  )

  fun load(): NbgLearnedSkillDraftQueue =
    parseNbgLearnedSkillDraftQueue(storage.read())

  fun save(queue: NbgLearnedSkillDraftQueue): NbgLearnedSkillDraftQueue {
    val normalized = nbgBuildLearnedSkillDraftQueue(queue.entries)
    storage.write(normalized.toJsonString())
    return normalized
  }

  fun upsert(entry: NbgLearnedSkillDraftQueueEntry): NbgLearnedSkillDraftQueue =
    save(nbgBuildLearnedSkillDraftQueue(load().entries + maybeAutoApply(entry)))

  fun reject(id: String, nowMs: Long = System.currentTimeMillis()): NbgLearnedSkillDraftQueue {
    val cleanId = id.trim()
    if (cleanId.isBlank()) return load()
    val next = load().entries.map { entry ->
      if (entry.id == cleanId) {
        entry.copy(
          status = NbgLearnedSkillDraftStatus.Rejected,
          updatedAtMs = nowMs.coerceAtLeast(entry.updatedAtMs),
        )
      } else {
        entry
      }
    }
    return save(NbgLearnedSkillDraftQueue(next))
  }

  private fun maybeAutoApply(
    entry: NbgLearnedSkillDraftQueueEntry,
    nowMs: Long = System.currentTimeMillis(),
  ): NbgLearnedSkillDraftQueueEntry {
    val root = artifactRoot ?: return entry
    if (!entry.review.allowInstall || entry.status == NbgLearnedSkillDraftStatus.AutoApplied) return entry
    val skillDir = File(root, entry.skillName.nbgLearnedSkillArtifactDirName())
    val skillFile = File(skillDir, "SKILL.md")
    return runCatching {
      skillDir.mkdirs()
      val previous = if (skillFile.isFile) skillFile.readText(Charsets.UTF_8) else ""
      val previousSha = previous.takeIf { it.isNotBlank() }?.sha256Hex().orEmpty()
      val rollbackFile = if (previousSha.isNotBlank()) {
        File(skillDir, ".nbg-rollback/SKILL.${previousSha.take(12)}.md").also { backup ->
          backup.parentFile?.mkdirs()
          backup.writeText(previous, Charsets.UTF_8)
        }
      } else {
        null
      }
      skillFile.writeText(entry.toAutoAppliedSkillMarkdown(), Charsets.UTF_8)
      entry.withAutoAppliedArtifact(
        installPath = skillFile.absolutePath,
        rollbackPath = rollbackFile?.absolutePath.orEmpty(),
        previousArtifactSha256 = previousSha,
        autoEnable = entry.review.allowEnable,
        nowMs = nowMs,
      )
    }.getOrElse {
      entry
    }
  }
}

private fun String.nbgLearnedSkillArtifactDirName(): String =
  lowercase()
    .replace(Regex("[^a-z0-9_.-]+"), "-")
    .trim('-', '.', '_')
    .take(80)
    .ifBlank { "learned-skill" }

private fun NbgLearnedSkillDraftQueueEntry.toAutoAppliedSkillMarkdown(): String =
  """
  ---
  name: $skillName
  description: ${description.ifBlank { sourceTaskTitle }.ifBlank { "NBG learned Skill" }}
  version: 0.1.0
  author: NBG
  metadata:
    nbg:
      source_task_id: ${review.sourceTaskId}
      permission_tier: ${review.permissionTier.wireName}
      policy_version: ${review.policyVersion}
  ---

  # ${skillName.replace('-', ' ').replaceFirstChar { it.uppercase() }}

  ## When to Use
  ${description.ifBlank { sourceTaskTitle }.ifBlank { "Use this learned workflow when the same task pattern appears again." }}

  ## Safety
  - This Skill was generated by NBG autonomous learning.
  - It was auto-applied only because local policy marked it low/medium risk with complete evidence.
  - Review, disable, or reject it from the Skills/Learning surfaces if it is not useful.
  """.trimIndent()
